name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: echo "@BringBeyond:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=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" > .npmrc
      - run: npm i
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: "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"
